Documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/*', '.readthedocs.yml', 'logos/*', 'README.md']

Internal:
  - changed-files:
      - any-glob-to-any-file: ['.pre-commit-config.yaml', '.readthedocs.yml', 'codecov.yml', '.gitignore', '.github/*', 'nigsp/_version.py']

Testing:
  - changed-files:
      - any-glob-to-any-file: ['nigsp/tests/*', '.circleci/*']
