site_name: nigsp
site_description: nigsp | A module for graph signal processing on neuroimaging data
site_author: Stefano Moia
site_url: https://nigsp.github.io
site_dir: ./../.

repo_url: https://github.com/MIPLabCH/nigsp

# Copyright
copyright: Copyright &copy; 2022

plugins:
  - search
  - mkapi:
      src_dirs: [nigsp]

nav:
    - nigsp: index.md
    - Usage:
      - Installation: usage/installation.md
      - User Guide: usage/user_guide.md
      - Licence: usage/licence.md
      - Output: usage/output.md
    - API:
      - nigsp.workflow: api/workflow.md
      - nigsp.objects: api/objects.md
      - nigsp.io: api/io.md
      - nigsp.viz: api/viz.md
      - nigsp.utils: api/utils.md
      - nigsp.blocks: api/blocks.md
      - nigsp.operations: api/operations.md
    - Graph Signal Processing:
      - About GSP: about_gsp.md
    - Developers:
      - How to Contribute: developers/how_to_contribute.md
      - Contributor Guide: developers/contributor_guide.md 
      - Code of Conduct: developers/code_of_conduct.md

theme:
  name: readthedocs
  locale: en
  highlightjs: True
  hljs_languages:
    - yaml
    - python
    - shell
    - bash
    - markup
    - nohighlight
  sticky_navigation: False

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: "#"
      separator: "_"
